const fs = require('fs');

// =========================================================
// DERS 3 - TAM VERİ ÇIKARIMI
// Kaynak: balgoc___Bulgarca_A1_Ders_3_Turkce_Aciklamali_Not.docx
// =========================================================

// -------------------------------------------------------
// 1. KELİMELER - Diyalog + Tablo + Okuma'dan çıkarılan
// -------------------------------------------------------
const yeniKelimeler = [
  // --- TEMEL SELAMLAŞMA VE KONUŞMA KALIPLARI (Diyalog 1) ---
  { bg: "Добър ден", tr: "İyi günler", kategori: "selamlasma", ders: 3 },
  { bg: "Приятно ми е", tr: "Memnun oldum", kategori: "selamlasma", ders: 3 },
  { bg: "Как се казвате?", tr: "Adınız nedir? / Nasıl adlandırılıyorsunuz?", kategori: "selamlasma", ders: 3 },
  { bg: "Казвам се ...", tr: "Adım ... / Ben ... olarak adlandırılırım", kategori: "selamlasma", ders: 3 },
  { bg: "Откъде сте?", tr: "Nerelisiniz?", kategori: "selamlasma", ders: 3 },
  { bg: "Откъде си?", tr: "Nerelisin?", kategori: "selamlasma", ders: 3 },
  { bg: "Откъде е?", tr: "O nereli?", kategori: "selamlasma", ders: 3 },
  { bg: "Разбира се", tr: "Elbette / Tabii ki", kategori: "selamlasma", ders: 3 },
  { bg: "Благодаря", tr: "Teşekkür ederim", kategori: "selamlasma", ders: 3 },
  { bg: "Благодаря за информацията", tr: "Bilgi için teşekkür ederim", kategori: "selamlasma", ders: 3 },
  { bg: "Довиждане", tr: "Hoşça kalın / Görüşürüz", kategori: "selamlasma", ders: 3 },
  { bg: "Приятен ден", tr: "İyi günler (veda)", kategori: "selamlasma", ders: 3 },
  { bg: "До скоро", tr: "Yakında görüşürüz / Yakında", kategori: "selamlasma", ders: 3 },
  { bg: "Беше ми приятно", tr: "Keyifli geçti / Memnun oldum", kategori: "selamlasma", ders: 3 },
  { bg: "Радвам се, че се запознахме", tr: "Tanıştığımıza sevindim", kategori: "selamlasma", ders: 3 },
  { bg: "Надявам се скоро да се видим", tr: "Umarım yakında görüşürüz", kategori: "selamlasma", ders: 3 },
  { bg: "Може би", tr: "Belki", kategori: "selamlasma", ders: 3 },
  { bg: "Светът е малък", tr: "Dünya küçüktür", kategori: "selamlasma", ders: 3 },
  { bg: "Елате ми на гости", tr: "Bana misafirliğe gelin", kategori: "selamlasma", ders: 3 },

  // --- HİTAPLAR ---
  { bg: "госпожице", tr: "bayan / hanımefendi (genç/bekar)", kategori: "hitap", ders: 3 },
  { bg: "госпожо", tr: "hanımefendi (evli/yaşlı)", kategori: "hitap", ders: 3 },
  { bg: "господин", tr: "bay / bey", kategori: "hitap", ders: 3 },
  { bg: "господинът", tr: "bay (belirli)", kategori: "hitap", ders: 3 },
  { bg: "професор", tr: "profesör", kategori: "hitap", ders: 3 },

  // --- ZAMİRLER VE GÖSTERME SÖZCÜKLERI ---
  { bg: "аз", tr: "ben", kategori: "zamir", ders: 3 },
  { bg: "ти", tr: "sen", kategori: "zamir", ders: 3 },
  { bg: "той", tr: "o (erkek)", kategori: "zamir", ders: 3 },
  { bg: "тя", tr: "o (kadın)", kategori: "zamir", ders: 3 },
  { bg: "то", tr: "o (nötr)", kategori: "zamir", ders: 3 },
  { bg: "ние", tr: "biz", kategori: "zamir", ders: 3 },
  { bg: "вие", tr: "siz", kategori: "zamir", ders: 3 },
  { bg: "те", tr: "onlar", kategori: "zamir", ders: 3 },
  { bg: "Вие", tr: "Siz (saygı)", kategori: "zamir", ders: 3 },
  { bg: "това", tr: "bu (eril/nötr için)", kategori: "zamir", ders: 3 },
  { bg: "тази", tr: "bu (dişil isimler için)", kategori: "zamir", ders: 3 },
  { bg: "онзи", tr: "şu / öteki (eril)", kategori: "zamir", ders: 3 },
  { bg: "го", tr: "onu (eril nesne zamiri)", kategori: "zamir", ders: 3 },
  { bg: "Това са", tr: "Bunlar ...dır", kategori: "zamir", ders: 3 },
  { bg: "коя", tr: "kim? (dişil)", kategori: "zamir", ders: 3 },
  { bg: "кой", tr: "kim? (eril)", kategori: "zamir", ders: 3 },

  // --- OLMAK FİİLİ (СЪМ) ---
  { bg: "Аз съм", tr: "Ben ... im / var", kategori: "fiil_olmak", ders: 3 },
  { bg: "Ти си", tr: "Sen ... sin", kategori: "fiil_olmak", ders: 3 },
  { bg: "Той/тя/то е", tr: "O ... dir", kategori: "fiil_olmak", ders: 3 },
  { bg: "Ние сме", tr: "Biz ... iz", kategori: "fiil_olmak", ders: 3 },
  { bg: "Вие сте", tr: "Siz ... siniz", kategori: "fiil_olmak", ders: 3 },
  { bg: "Те са", tr: "Onlar ... dir", kategori: "fiil_olmak", ders: 3 },

  // --- ÜLKELER ---
  { bg: "България", tr: "Bulgaristan", kategori: "ulke", ders: 3 },
  { bg: "Турция", tr: "Türkiye", kategori: "ulke", ders: 3 },
  { bg: "Гърция", tr: "Yunanistan", kategori: "ulke", ders: 3 },
  { bg: "Албания", tr: "Arnavutluk", kategori: "ulke", ders: 3 },
  { bg: "Румъния", tr: "Romanya", kategori: "ulke", ders: 3 },
  { bg: "Сърбия", tr: "Sırbistan", kategori: "ulke", ders: 3 },
  { bg: "Македония", tr: "Makedonya", kategori: "ulke", ders: 3 },
  { bg: "Словения", tr: "Slovenya", kategori: "ulke", ders: 3 },
  { bg: "Босна", tr: "Bosna", kategori: "ulke", ders: 3 },
  { bg: "Херцеговина", tr: "Hersek", kategori: "ulke", ders: 3 },
  { bg: "Черна гора", tr: "Karadağ", kategori: "ulke", ders: 3 },
  { bg: "Украйна", tr: "Ukrayna", kategori: "ulke", ders: 3 },
  { bg: "Аржентина", tr: "Arjantin", kategori: "ulke", ders: 3 },
  { bg: "Унгария", tr: "Macaristan", kategori: "ulke", ders: 3 },
  { bg: "Канада", tr: "Kanada", kategori: "ulke", ders: 3 },
  { bg: "Австралия", tr: "Avustralya", kategori: "ulke", ders: 3 },
  { bg: "Германия", tr: "Almanya", kategori: "ulke", ders: 3 },
  { bg: "Франция", tr: "Fransa", kategori: "ulke", ders: 3 },
  { bg: "Италия", tr: "İtalya", kategori: "ulke", ders: 3 },
  { bg: "Русия", tr: "Rusya", kategori: "ulke", ders: 3 },
  { bg: "САЩ", tr: "ABD", kategori: "ulke", ders: 3 },
  { bg: "Иран", tr: "İran", kategori: "ulke", ders: 3 },
  { bg: "Ирак", tr: "Irak", kategori: "ulke", ders: 3 },
  { bg: "Сирия", tr: "Suriye", kategori: "ulke", ders: 3 },
  { bg: "Грузия", tr: "Gürcistan", kategori: "ulke", ders: 3 },
  { bg: "Армения", tr: "Ermenistan", kategori: "ulke", ders: 3 },

  // --- ŞEHİRLER ---
  { bg: "София", tr: "Sofya", kategori: "sehir", ders: 3 },
  { bg: "Истанбул", tr: "İstanbul", kategori: "sehir", ders: 3 },
  { bg: "Измир", tr: "İzmir", kategori: "sehir", ders: 3 },
  { bg: "Одрин", tr: "Edirne", kategori: "sehir", ders: 3 },
  { bg: "Бурса", tr: "Bursa", kategori: "sehir", ders: 3 },
  { bg: "Антакия", tr: "Antakya", kategori: "sehir", ders: 3 },
  { bg: "Такирдаг", tr: "Tekirdağ", kategori: "sehir", ders: 3 },
  { bg: "Париж", tr: "Paris", kategori: "sehir", ders: 3 },

  // --- MİLLİYETLER (eril) ---
  { bg: "българин", tr: "Bulgar (erkek)", kategori: "milliyet", ders: 3 },
  { bg: "турчин", tr: "Türk (erkek)", kategori: "milliyet", ders: 3 },
  { bg: "грък", tr: "Yunan (erkek)", kategori: "milliyet", ders: 3 },
  { bg: "албанец", tr: "Arnavut (erkek)", kategori: "milliyet", ders: 3 },
  { bg: "румънец", tr: "Romen (erkek)", kategori: "milliyet", ders: 3 },
  { bg: "руснак", tr: "Rus (erkek)", kategori: "milliyet", ders: 3 },
  { bg: "американец", tr: "Amerikalı (erkek)", kategori: "milliyet", ders: 3 },
  { bg: "французин", tr: "Fransız (erkek)", kategori: "milliyet", ders: 3 },
  { bg: "италианец", tr: "İtalyan (erkek)", kategori: "milliyet", ders: 3 },
  { bg: "германец", tr: "Alman (erkek)", kategori: "milliyet", ders: 3 },

  // --- MİLLİYETLER (dişil) ---
  { bg: "българка", tr: "Bulgar (kadın)", kategori: "milliyet", ders: 3 },
  { bg: "туркиня", tr: "Türk (kadın)", kategori: "milliyet", ders: 3 },
  { bg: "гъркиня", tr: "Yunan (kadın)", kategori: "milliyet", ders: 3 },
  { bg: "рускиня", tr: "Rus (kadın)", kategori: "milliyet", ders: 3 },
  { bg: "американка", tr: "Amerikalı (kadın)", kategori: "milliyet", ders: 3 },
  { bg: "французойка", tr: "Fransız (kadın)", kategori: "milliyet", ders: 3 },
  { bg: "италианка", tr: "İtalyan (kadın)", kategori: "milliyet", ders: 3 },

  // --- MESLEKLERereden (Diyalog 2) ---
  { bg: "студент", tr: "öğrenci (erkek)", kategori: "meslek", ders: 3 },
  { bg: "студентка", tr: "öğrenci (kadın)", kategori: "meslek", ders: 3 },
  { bg: "преподавател", tr: "öğretim görevlisi (erkek)", kategori: "meslek", ders: 3 },
  { bg: "преподавателка", tr: "öğretim görevlisi (kadın)", kategori: "meslek", ders: 3 },
  { bg: "учител", tr: "öğretmen (erkek)", kategori: "meslek", ders: 3 },
  { bg: "учителка", tr: "öğretmen (kadın)", kategori: "meslek", ders: 3 },
  { bg: "лекар", tr: "doktor (erkek)", kategori: "meslek", ders: 3 },
  { bg: "лекарка", tr: "doktor (kadın)", kategori: "meslek", ders: 3 },
  { bg: "медицинска сестра", tr: "hemşire", kategori: "meslek", ders: 3 },
  { bg: "санитарка", tr: "hasta bakıcı / sağlık görevlisi (kadın)", kategori: "meslek", ders: 3 },
  { bg: "инженер", tr: "mühendis", kategori: "meslek", ders: 3 },
  { bg: "строителен инженер", tr: "inşaat mühendisi", kategori: "meslek", ders: 3 },
  { bg: "архитект", tr: "mimar", kategori: "meslek", ders: 3 },
  { bg: "строител", tr: "inşaatçı", kategori: "meslek", ders: 3 },
  { bg: "зъболекар", tr: "diş hekimi", kategori: "meslek", ders: 3 },
  { bg: "счетоводител", tr: "muhasebeci", kategori: "meslek", ders: 3 },
  { bg: "бизнесмен", tr: "iş insanı", kategori: "meslek", ders: 3 },
  { bg: "банкер", tr: "bankacı", kategori: "meslek", ders: 3 },
  { bg: "художничка", tr: "ressam (kadın)", kategori: "meslek", ders: 3 },
  { bg: "моделиер", tr: "modelist (erkek)", kategori: "meslek", ders: 3 },
  { bg: "моделиерка", tr: "modelist (kadın)", kategori: "meslek", ders: 3 },
  { bg: "дизайнер", tr: "tasarımcı", kategori: "meslek", ders: 3 },
  { bg: "аранжьор", tr: "vitrin/dekor düzenleyici", kategori: "meslek", ders: 3 },
  { bg: "шивачка", tr: "terzi (kadın)", kategori: "meslek", ders: 3 },
  { bg: "продавачка", tr: "satıcı (kadın)", kategori: "meslek", ders: 3 },
  { bg: "сервитьор", tr: "garson (erkek)", kategori: "meslek", ders: 3 },
  { bg: "книжар", tr: "kitapçı", kategori: "meslek", ders: 3 },
  { bg: "вестникар", tr: "gazete satıcısı", kategori: "meslek", ders: 3 },
  { bg: "печатар", tr: "matbaacı", kategori: "meslek", ders: 3 },
  { bg: "таксиметров шофьор", tr: "taksi şoförü", kategori: "meslek", ders: 3 },
  { bg: "ватман", tr: "tramvay sürücüsü", kategori: "meslek", ders: 3 },
  { bg: "редактор", tr: "editör", kategori: "meslek", ders: 3 },
  { bg: "маникюристка", tr: "manikürcü (kadın)", kategori: "meslek", ders: 3 },
  { bg: "фризьорка", tr: "kuaför (kadın)", kategori: "meslek", ders: 3 },
  { bg: "журналист", tr: "gazeteci", kategori: "meslek", ders: 3 },
  { bg: "репортер", tr: "muhabir / röportajcı", kategori: "meslek", ders: 3 },
  { bg: "компютърен специалист", tr: "bilgisayar uzmanı", kategori: "meslek", ders: 3 },
  { bg: "преводачка", tr: "çevirmen (kadın)", kategori: "meslek", ders: 3 },
  { bg: "секретарка", tr: "sekreter (kadın)", kategori: "meslek", ders: 3 },

  // --- AİLE ÜYELERİ ---
  { bg: "майка", tr: "anne", kategori: "aile", ders: 3 },
  { bg: "майка ми", tr: "annem", kategori: "aile", ders: 3 },
  { bg: "баща", tr: "baba", kategori: "aile", ders: 3 },
  { bg: "баща ми", tr: "babam", kategori: "aile", ders: 3 },
  { bg: "дядо ми", tr: "dedem", kategori: "aile", ders: 3 },
  { bg: "брат ми", tr: "erkek kardeşim", kategori: "aile", ders: 3 },
  { bg: "сестра", tr: "kız kardeş", kategori: "aile", ders: 3 },
  { bg: "родителите", tr: "anne baba / ebeveynler", kategori: "aile", ders: 3 },

  // --- MEKANLAR VE KURUMLAR ---
  { bg: "университет", tr: "üniversite", kategori: "kurum", ders: 3 },
  { bg: "катедра", tr: "bölüm / anabilim dalı", kategori: "kurum", ders: 3 },
  { bg: "болница", tr: "hastane", kategori: "kurum", ders: 3 },
  { bg: "магазин за облекло", tr: "giyim mağazası", kategori: "kurum", ders: 3 },
  { bg: "нощен ресторант", tr: "gece restoranı", kategori: "kurum", ders: 3 },
  { bg: "печатница", tr: "matbaa", kategori: "kurum", ders: 3 },
  { bg: "фризьорски салон", tr: "kuaför salonu", kategori: "kurum", ders: 3 },
  { bg: "модна къща", tr: "moda evi", kategori: "kurum", ders: 3 },
  { bg: "Медицинска академия", tr: "Tıp Akademisi", kategori: "kurum", ders: 3 },
  { bg: "Икономическия институт", tr: "İktisat Enstitüsü", kategori: "kurum", ders: 3 },
  { bg: "Инженерно-строителния институт", tr: "Mühendislik-İnşaat Enstitüsü", kategori: "kurum", ders: 3 },

  // --- YÖNLER VE COĞRAFYA ---
  { bg: "север", tr: "kuzey", kategori: "yonler", ders: 3 },
  { bg: "юг", tr: "güney", kategori: "yonler", ders: 3 },
  { bg: "изток", tr: "doğu", kategori: "yonler", ders: 3 },
  { bg: "запад", tr: "batı", kategori: "yonler", ders: 3 },
  { bg: "северозапад", tr: "kuzeybatı", kategori: "yonler", ders: 3 },
  { bg: "североизток", tr: "kuzeydoğu", kategori: "yonler", ders: 3 },
  { bg: "югозапад", tr: "güneybatı", kategori: "yonler", ders: 3 },
  { bg: "югоизток", tr: "güneydoğu", kategori: "yonler", ders: 3 },
  { bg: "граничи с", tr: "ile sınır komşusudur", kategori: "yonler", ders: 3 },
  { bg: "граница", tr: "sınır", kategori: "yonler", ders: 3 },
  { bg: "съсед", tr: "komşu", kategori: "yonler", ders: 3 },
  { bg: "Черно море", tr: "Karadeniz", kategori: "yonler", ders: 3 },
  { bg: "Мраморно море", tr: "Marmara Denizi", kategori: "yonler", ders: 3 },
  { bg: "Егейско море", tr: "Ege Denizi", kategori: "yonler", ders: 3 },
  { bg: "Средиземно море", tr: "Akdeniz", kategori: "yonler", ders: 3 },

  // --- TEMEL FİİLLER ---
  { bg: "следвам", tr: "okumak (üniversitede)", kategori: "fiil", ders: 3 },
  { bg: "работя", tr: "çalışırım", kategori: "fiil", ders: 3 },
  { bg: "работят", tr: "çalışırlar", kategori: "fiil", ders: 3 },
  { bg: "говоря", tr: "konuşurum", kategori: "fiil", ders: 3 },
  { bg: "искам да стана", tr: "... olmak istiyorum", kategori: "fiil", ders: 3 },
  { bg: "ще бъда", tr: "... olacağım (gelecek)", kategori: "fiil", ders: 3 },
  { bg: "мечтае да стане", tr: "... olmayı hayal ediyor", kategori: "fiil", ders: 3 },
  { bg: "познавате ли го?", tr: "Onu tanıyor musunuz?", kategori: "fiil", ders: 3 },
  { bg: "представя", tr: "takdim etmek / tanıtmak", kategori: "fiil", ders: 3 },
  { bg: "запознаем се", tr: "tanışacağız", kategori: "fiil", ders: 3 },
  { bg: "разрешете", tr: "izin verin", kategori: "fiil", ders: 3 },

  // --- SIFATLAR VE ZARFLAR ---
  { bg: "много хубаво", tr: "çok güzel", kategori: "sifat", ders: 3 },
  { bg: "различни", tr: "farklı", kategori: "sifat", ders: 3 },
  { bg: "труден/трудно", tr: "zor", kategori: "sifat", ders: 3 },
  { bg: "зает", tr: "meşgul", kategori: "sifat", ders: 3 },
  { bg: "любезен", tr: "nazik / kibar", kategori: "sifat", ders: 3 },
  { bg: "интензивно", tr: "yoğun biçimde", kategori: "sifat", ders: 3 },
  { bg: "особено", tr: "özellikle", kategori: "sifat", ders: 3 },
  { bg: "малко", tr: "az / biraz", kategori: "sifat", ders: 3 },
  { bg: "вече", tr: "artık / şimdiden", kategori: "sifat", ders: 3 },
  { bg: "скоро", tr: "yakında", kategori: "sifat", ders: 3 },

  // --- SORU YAPILARI ---
  { bg: "Какъв/каква сте по националност?", tr: "Milliyetiniz nedir?", kategori: "soru", ders: 3 },
  { bg: "Турчин ли сте?", tr: "Türk erkek misiniz?", kategori: "soru", ders: 3 },
  { bg: "Туркиня ли сте?", tr: "Türk kadın mısınız?", kategori: "soru", ders: 3 },
  { bg: "От коя държава си?", tr: "Hangi ülkedensin?", kategori: "soru", ders: 3 },
  { bg: "Какво правите в София?", tr: "Sofya'da ne yapıyorsunuz?", kategori: "soru", ders: 3 },
  { bg: "В кой курс сте?", tr: "Hangi sınıftasınız?", kategori: "soru", ders: 3 },
  { bg: "Каква специалност?", tr: "Hangi bölüm?", kategori: "soru", ders: 3 },
  { bg: "А родителите Ви какви са?", tr: "Peki anne babanız ne iş yapıyor?", kategori: "soru", ders: 3 },
  { bg: "ли", tr: "mı/mi/mu/mü (soru edatı)", kategori: "soru", ders: 3 },
];

// -------------------------------------------------------
// 2. SORULAR - Diyalog + Gramer + Okuma'dan çıkarılan
// -------------------------------------------------------
function makeId() {
  return 'd3_' + Math.random().toString(36).substring(2, 10);
}

const yeniSorular = [
  // ===== BÖLÜM 1: DİYALOG ANLAMA =====
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["diyalog", "anlama", "ders3"],
    question: 'Diyalogda Bülent nerelidir?',
    options: ["Sofya'dan", "İzmir'den", "İstanbul'dan", "Edirne'den"],
    answer: "İstanbul'dan",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["diyalog", "anlama", "ders3"],
    question: 'Diyalogda Sevil nerelidir?',
    options: ["İstanbul'dan", "Edirne'den", "Sofya'dan", "İzmir'den"],
    answer: "İzmir'den",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["diyalog", "anlama", "ders3"],
    question: 'Diyalogda Cevriye nereden gelmiştir?',
    options: ["İstanbul'dan", "Sofya'dan", "İzmir'den", "Edirne'den"],
    answer: "Edirne'den",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["diyalog", "anlama", "ders3"],
    question: 'Profesör Raynov hangi ülkedendir?',
    options: ["Yunanistan'dan", "Türkiye'den", "Arnavutluk'tan", "Bulgaristan'dan"],
    answer: "Bulgaristan'dan",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["diyalog", "anlama", "ders3"],
    question: 'Diyalogda Profesör Petrovа\'nın milliyeti nedir?',
    options: ["Yunan kadın", "Arnavut erkek", "Bulgar kadın", "Rus kadın"],
    answer: "Bulgar kadın",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["diyalog", "anlama", "ders3"],
    question: '"Беше ми приятно да се запознаем" ne anlama gelir?',
    options: ["Tanışmak istiyorum", "Tanıştığımıza memnun oldum", "Nerelisiniz?", "İyi günler"],
    answer: "Tanıştığımıza memnun oldum",
    points: 1,
  },

  // ===== BÖLÜM 2: ÇEVİRİ - BG → TR =====
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["ceviri", "selamlasma", "ders3"],
    question: '"Откъде сте?" ne anlama gelir?',
    options: ["Kim misiniz?", "Nerelisiniz?", "Adınız ne?", "Nereye gidiyorsunuz?"],
    answer: "Nerelisiniz?",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["ceviri", "selamlasma", "ders3"],
    question: '"Приятно ми е" ne anlama gelir?',
    options: ["İyi günler", "Hoşça kalın", "Memnun oldum", "Teşekkür ederim"],
    answer: "Memnun oldum",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["ceviri", "selamlasma", "ders3"],
    question: '"Разбира се" ne anlama gelir?',
    options: ["Belki", "Elbette / Tabii ki", "Hayır", "Umarım"],
    answer: "Elbette / Tabii ki",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["ceviri", "selamlasma", "ders3"],
    question: '"Довиждане" ne anlama gelir?',
    options: ["İyi günler", "Memnun oldum", "Teşekkürler", "Hoşça kalın / Görüşürüz"],
    answer: "Hoşça kalın / Görüşürüz",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["ceviri", "selamlasma", "ders3"],
    question: '"Благодаря за информацията" ne anlama gelir?',
    options: ["Bilgi için teşekkür ederim", "Memnun oldum", "Bunu anlıyorum", "Elbette"],
    answer: "Bilgi için teşekkür ederim",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["ceviri", "selamlasma", "ders3"],
    question: '"Казвам се Севил" ne anlama gelir?',
    options: ["Sevil'i arıyorum", "Adım Sevil", "Ben Sevil değilim", "Sevil buraya gel"],
    answer: "Adım Sevil",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["ceviri", "ders3"],
    question: '"Ще се запознаем с тях" ne anlama gelir?',
    options: ["Onlarla görüştük", "Onları tanıyorum", "Onlarla tanışacağız", "Onları görmeyiz"],
    answer: "Onlarla tanışacağız",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["ceviri", "ders3"],
    question: '"Светът е малък" ne anlama gelir?',
    options: ["Dünya büyüktür", "Dünya küçüktür", "Şehir küçüktür", "Bu küçük bir şey"],
    answer: "Dünya küçüktür",
    points: 1,
  },

  // ===== BÖLÜM 3: ÇEVİRİ - TR → BG =====
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["ceviri", "tr_bg", "ders3"],
    question: '"Nerelisiniz?" Bulgarcası nedir?',
    options: ["Как се казвате?", "Откъде сте?", "Коя е?", "Откъде е?"],
    answer: "Откъде сте?",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["ceviri", "tr_bg", "ders3"],
    question: '"İyi günler" Bulgarcası nedir?',
    options: ["Довиждане", "Благодаря", "Добър ден", "Приятно ми е"],
    answer: "Добър ден",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["ceviri", "tr_bg", "ders3"],
    question: '"Teşekkür ederim" Bulgarcası nedir?',
    options: ["Разбира се", "Приятно ми е", "Довиждане", "Благодаря"],
    answer: "Благодаря",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["ceviri", "tr_bg", "ders3"],
    question: '"Adım Sevil" Bulgarcası nedir?',
    options: ["Аз съм Севил", "Казвам се Севил", "Тя е Севил", "Меня зовут Севил"],
    answer: "Казвам се Севил",
    points: 1,
  },

  // ===== BÖLÜM 4: OLMAK FİİLİ (СЪМ) =====
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "fill_blank",
    difficulty: "easy",
    tags: ["gramer", "olmak_fiili", "ders3"],
    question: '"Аз ____ от Турция." cümlesini tamamlayın.',
    options: ["си", "е", "съм", "сме"],
    answer: "съм",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "fill_blank",
    difficulty: "easy",
    tags: ["gramer", "olmak_fiili", "ders3"],
    question: '"Той ____ студент." cümlesini tamamlayın.',
    options: ["съм", "си", "е", "са"],
    answer: "е",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "fill_blank",
    difficulty: "easy",
    tags: ["gramer", "olmak_fiili", "ders3"],
    question: '"Те ____ студенти." cümlesini tamamlayın.',
    options: ["е", "си", "съм", "са"],
    answer: "са",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "fill_blank",
    difficulty: "easy",
    tags: ["gramer", "olmak_fiili", "ders3"],
    question: '"Вие ____ от България." cümlesini tamamlayın.',
    options: ["съм", "са", "е", "сте"],
    answer: "сте",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "fill_blank",
    difficulty: "easy",
    tags: ["gramer", "olmak_fiili", "ders3"],
    question: '"Ние ____ студенти." cümlesini tamamlayın.',
    options: ["сте", "е", "сме", "са"],
    answer: "сме",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["gramer", "olmak_fiili", "ders3"],
    question: '"Ти" (sen) için doğru olmak fiili biçimi hangisidir?',
    options: ["съм", "е", "си", "сте"],
    answer: "си",
    points: 1,
  },

  // ===== BÖLÜM 5: MİLLİYETLER =====
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["milliyet", "ders3"],
    question: '"Türk erkek" Bulgarcası nedir?',
    options: ["туркиня", "турчин", "турски", "турка"],
    answer: "турчин",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["milliyet", "ders3"],
    question: '"Türk kadın" Bulgarcası nedir?',
    options: ["туркиня", "турчин", "турска жена", "туркинята"],
    answer: "туркиня",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["milliyet", "ders3"],
    question: '"Bulgar erkek" Bulgarcası nedir?',
    options: ["българка", "България", "български", "българин"],
    answer: "българин",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["milliyet", "ders3"],
    question: '"Yunan erkek" Bulgarcası nedir?',
    options: ["гъркиня", "гърция", "грък", "гръцки"],
    answer: "грък",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["milliyet", "ders3"],
    question: '"Yunan kadın" Bulgarcası nedir?',
    options: ["грък", "гъркиня", "гърция", "гъркин"],
    answer: "гъркиня",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["milliyet", "ders3"],
    question: '"Romen erkek" Bulgarcası nedir?',
    options: ["рускиня", "română", "румък", "румънец"],
    answer: "румънец",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["milliyet", "ders3"],
    question: '"Arnavut erkek" Bulgarcası nedir?',
    options: ["albaneci", "алтайски", "албанка", "албанец"],
    answer: "албанец",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "hard",
    tags: ["milliyet", "ders3"],
    question: 'Окума metnine göre "Нikos е ____."',
    options: ["рускиня", "туркиня", "грък", "румънец"],
    answer: "грък",
    points: 2,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "hard",
    tags: ["milliyet", "ders3"],
    question: 'Окuma metnine göre "Мирча е ____."',
    options: ["грък", "румънец", "рускиня", "туркиня"],
    answer: "румънец",
    points: 2,
  },

  // ===== BÖLÜM 6: ÜLKELER =====
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["ulke", "ders3"],
    question: '"Bulgaristan" Bulgarcası nedir?',
    options: ["Бурса", "Буgaristan", "Балкан", "България"],
    answer: "България",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["ulke", "ders3"],
    question: '"Yunanistan" Bulgarcası nedir?',
    options: ["Гърция", "Румъния", "Германия", "Грузия"],
    answer: "Гърция",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["ulke", "ders3"],
    question: '"Arnavutluk" Bulgarcası nedir?',
    options: ["Армения", "Австрия", "Аржентина", "Албания"],
    answer: "Албания",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["ulke", "ders3"],
    question: '"Romanya" Bulgarcası nedir?',
    options: ["Русия", "Румъния", "Сърбия", "Македония"],
    answer: "Румъния",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["ulke", "ders3"],
    question: '"ABD" Bulgarcası nedir?',
    options: ["АДС", "США", "САЩ", "СШЩ"],
    answer: "САЩ",
    points: 1,
  },

  // ===== BÖLÜM 7: MESLEKLER =====
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["meslek", "ders3"],
    question: '"Öğrenci (erkek)" Bulgarcası nedir?',
    options: ["студентка", "учител", "студент", "ученик"],
    answer: "студент",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["meslek", "ders3"],
    question: '"Öğrenci (kadın)" Bulgarcası nedir?',
    options: ["студент", "учителка", "студентка", "ученичка"],
    answer: "студентка",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["meslek", "ders3"],
    question: '"Лекар" ne anlama gelir?',
    options: ["hemşire", "diş hekimi", "doktor", "öğretmen"],
    answer: "doktor",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["meslek", "ders3"],
    question: '"Учител" ne anlama gelir?',
    options: ["öğrenci", "doktor", "mühendis", "öğretmen"],
    answer: "öğretmen",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["meslek", "ders3"],
    question: '"Архитект" ne anlama gelir?',
    options: ["mühendis", "inşaatçı", "tasarımcı", "mimar"],
    answer: "mimar",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["meslek", "ders3"],
    question: '"Зъболекар" ne anlama gelir?',
    options: ["doktor", "hemşire", "diş hekimi", "eczacı"],
    answer: "diş hekimi",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["meslek", "ders3"],
    question: '"Медицинска сестра" ne anlama gelir?',
    options: ["doktor", "hemşire", "hasta bakıcı", "ebe"],
    answer: "hemşire",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["meslek", "ders3"],
    question: '"Сервитьор" ne anlama gelir?',
    options: ["aşçı", "garson", "kasiyer", "satıcı"],
    answer: "garson",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["meslek", "ders3"],
    question: '"Ватман" ne anlama gelir?',
    options: ["taksi şoförü", "pilot", "tramvay sürücüsü", "otobüs sürücüsü"],
    answer: "tramvay sürücüsü",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["meslek", "ders3"],
    question: '"Фризьорка" ne anlama gelir?',
    options: ["manikürcü", "kuaför", "terzi", "satıcı"],
    answer: "kuaför",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "hard",
    tags: ["meslek", "ders3"],
    question: '"Счетоводител" ne anlama gelir?',
    options: ["muhasebeci", "bankacı", "iş insanı", "editör"],
    answer: "muhasebeci",
    points: 2,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "hard",
    tags: ["meslek", "ders3"],
    question: '"Репортер" ne anlama gelir?',
    options: ["editör", "gazeteci", "muhabir/röportajcı", "yazar"],
    answer: "muhabir/röportajcı",
    points: 2,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "hard",
    tags: ["meslek", "ders3"],
    question: 'Diyalogda kız kardeş mesleki olarak ressam iken, nerede çalışmaktadır?',
    options: ["hastanede", "okulda", "moda evinde", "matbaada"],
    answer: "moda evinde",
    points: 2,
  },

  // ===== BÖLÜM 8: AİLE ÜYELERİ =====
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["aile", "ders3"],
    question: '"Майка ми" ne anlama gelir?',
    options: ["babam", "kardeşim", "annem", "dedem"],
    answer: "annem",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["aile", "ders3"],
    question: '"Баща ми" ne anlama gelir?',
    options: ["dedem", "babam", "amcam", "kardeşim"],
    answer: "babam",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["aile", "ders3"],
    question: '"Брат ми" ne anlama gelir?',
    options: ["kız kardeşim", "babam", "erkek kardeşim", "amcam"],
    answer: "erkek kardeşim",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["aile", "ders3"],
    question: 'Diyalogda konuşan kişinin babası hangi meslektedir?',
    options: ["mühendis", "öğretmen", "doktor", "inşaatçı"],
    answer: "öğretmen",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["aile", "ders3"],
    question: 'Diyalogda konuşan kişinin annesi hangi meslektedir?',
    options: ["öğretmen", "hemşire", "sekreter", "doktor"],
    answer: "doktor",
    points: 1,
  },

  // ===== BÖLÜM 9: YÖNLER VE COĞRAFYA =====
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["cografi", "yonler", "ders3"],
    question: '"Север" ne anlama gelir?',
    options: ["güney", "doğu", "batı", "kuzey"],
    answer: "kuzey",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["cografi", "yonler", "ders3"],
    question: '"Юг" ne anlama gelir?',
    options: ["kuzey", "doğu", "güney", "batı"],
    answer: "güney",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["cografi", "yonler", "ders3"],
    question: '"Изток" ne anlama gelir?',
    options: ["batı", "kuzey", "güney", "doğu"],
    answer: "doğu",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "easy",
    tags: ["cografi", "yonler", "ders3"],
    question: '"Запад" ne anlama gelir?',
    options: ["doğu", "batı", "kuzey", "güney"],
    answer: "batı",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["cografi", "yonler", "ders3"],
    question: '"Северозапад" ne anlama gelir?',
    options: ["kuzeydoğu", "güneybatı", "kuzeybatı", "güneydoğu"],
    answer: "kuzeybatı",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["cografi", "ders3"],
    question: 'Metne göre Türkiye kuzeybatıda hangi ülkelerle sınır komşusudur?',
    options: ["İran ve Irak", "Gürcistan ve Ermenistan", "Bulgaristan ve Yunanistan", "Sırbistan ve Makedonya"],
    answer: "Bulgaristan ve Yunanistan",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["cografi", "ders3"],
    question: '"Черно море" ne anlama gelir?',
    options: ["Ege Denizi", "Akdeniz", "Marmara Denizi", "Karadeniz"],
    answer: "Karadeniz",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "hard",
    tags: ["cografi", "ders3"],
    question: 'Metne göre Bulgaristan\'ın güneyinde hangi ülkeler bulunmaktadır?',
    options: ["Romanya ve Sırbistan", "Türkiye ve Yunanistan", "Makedonya ve Arnavutluk", "Sırbistan ve Makedonya"],
    answer: "Türkiye ve Yunanistan",
    points: 2,
  },

  // ===== BÖLÜM 10: OKUMA METNİ - "Какъв съм аз?" =====
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["okuma", "ders3"],
    question: 'Okuma metnine göre Rayna ve İvan ne okumaktadır?',
    options: ["Hukuk", "Tıp", "İnşaat Mühendisliği", "Bulgar Filolojisi"],
    answer: "Bulgar Filolojisi",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["okuma", "ders3"],
    question: 'Okuma metnine göre Emine\'nin milliyeti nedir?',
    options: ["Rus kadın", "Romen erkek", "Bulgar kadın", "Türk kadın"],
    answer: "Türk kadın",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "hard",
    tags: ["okuma", "ders3"],
    question: 'Okuma metnine göre ABD\'den John hangi kökenlidir?',
    options: ["Arnavut kökenli", "Bulgar kökenli", "Rus kökenli", "Yunan kökenli"],
    answer: "Bulgar kökenli",
    points: 2,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "hard",
    tags: ["okuma", "ders3"],
    question: '"Те следват българска филология" ne anlama gelir?',
    options: ["Bulgar Filolojisi okuyorlar", "Bulgarca konuşuyorlar", "Bulgaristan'da yaşıyorlar", "Bulgarca öğreniyorlar"],
    answer: "Bulgar Filolojisi okuyorlar",
    points: 2,
  },

  // ===== BÖLÜM 11: DİYALOG 2 - "Искам да стана" =====
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["diyalog2", "ders3"],
    question: '"Искам да стана учителка по литература." ne anlama gelir?',
    options: ["Edebiyat öğretmeni olarak çalışıyorum", "Edebiyat öğretmeni olmak istiyorum", "Edebiyatçı olmak zorundayım", "Edebiyat okuyorum"],
    answer: "Edebiyat öğretmeni olmak istiyorum",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["diyalog2", "ders3"],
    question: '"Не, ще бъда архитект." ne anlama gelir?',
    options: ["Hayır, mühendis olmak istiyorum", "Hayır, inşaatçı olacağım", "Hayır, mimar olacağım", "Hayır, mimar olmak istemiyorum"],
    answer: "Hayır, mimar olacağım",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "hard",
    tags: ["diyalog2", "ders3"],
    question: '"Мечтае да стане бизнесмен или банкер." ne anlama gelir?',
    options: ["İş insanı veya bankacı olarak çalışıyor", "İş insanı ya da bankacı olmayı hayal ediyor", "İş insanı olmak istemiyor", "Bankacı olma hayali kurmuyor"],
    answer: "İş insanı ya da bankacı olmayı hayal ediyor",
    points: 2,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "hard",
    tags: ["diyalog2", "ders3"],
    question: 'Diyalog 2\'de kız arkadaşın mesleği nedir?',
    options: ["öğretim görevlisi", "muhabir / gazeteci", "hemşire", "terzi"],
    answer: "muhabir / gazeteci",
    points: 2,
  },

  // ===== BÖLÜM 12: GRAMER - GÖSTERME ZAMİRLERİ =====
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["gramer", "zamir", "ders3"],
    question: '"Тази" hangi cins isimler için kullanılır?',
    options: ["eril isimler için", "çoğul isimler için", "nötr isimler için", "dişil isimler için"],
    answer: "dişil isimler için",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["gramer", "zamir", "ders3"],
    question: '"Онзи" ne anlama gelir?',
    options: ["bu (eril)", "o (dişil)", "şu / öteki (eril)", "şu (dişil)"],
    answer: "şu / öteki (eril)",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["gramer", "zamir", "ders3"],
    question: '"Го" ne işlevi görür?',
    options: ["dişil nesne zamiri", "eril özne zamiri", "eril nesne zamiri", "çoğul nesne zamiri"],
    answer: "eril nesne zamiri",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "medium",
    tags: ["gramer", "zamir", "ders3"],
    question: '"Ли" ne işlevi görür?',
    options: ["olumlu cümle eki", "olumsuz cümle eki", "soru edatı", "zaman eki"],
    answer: "soru edatı",
    points: 1,
  },
  {
    id: makeId(),
    lesson: "Ders 3: Откъде сте?",
    type: "multiple_choice",
    difficulty: "hard",
    tags: ["gramer", "zamir", "ders3"],
    question: '"Ще + fiil" yapısı ne anlatır?',
    options: ["geçmiş zaman", "şimdiki zaman", "dilek kipi", "gelecek zaman"],
    answer: "gelecek zaman",
    points: 2,
  },
];

// Mevcut questions.json'a ekle
const mevcutSorular = JSON.parse(fs.readFileSync('src/data/questions.json', 'utf8'));
const yeniEklenenler = yeniSorular.filter(ys => !mevcutSorular.find(ms => ms.question === ys.question));
const tumSorular = [...mevcutSorular, ...yeniEklenenler];
fs.writeFileSync('src/data/questions.json', JSON.stringify(tumSorular, null, 2), 'utf8');
console.log(`✅ ${yeniEklenenler.length} yeni soru eklendi (toplam: ${tumSorular.length})`);

// Mevcut vocab_ders_3.json'a ek olarak yeni kelime listesini kaydet
const mevcutVocab = JSON.parse(fs.readFileSync('src/data/vocabulary/vocab_ders_3.json', 'utf8'));
const mevcutBGler = (mevcutVocab.words || []).map(w => w.bg);
const yeniKelimelerFiltered = yeniKelimeler.filter(k => !mevcutBGler.includes(k.bg));

mevcutVocab.words = [...(mevcutVocab.words || []), ...yeniKelimelerFiltered.map((k, i) => ({
  id: `d3_word_${Date.now()}_${i}`,
  bg: k.bg,
  tr: k.tr,
  category: k.kategori,
  lesson: k.ders,
  difficulty: "easy",
}))];

fs.writeFileSync('src/data/vocabulary/vocab_ders_3.json', JSON.stringify(mevcutVocab, null, 2), 'utf8');
console.log(`✅ ${yeniKelimelerFiltered.length} yeni kelime eklendi (toplam: ${mevcutVocab.words.length})`);

// Özet raporu
const kategoriler = {};
yeniKelimeler.forEach(k => { kategoriler[k.kategori] = (kategoriler[k.kategori] || 0) + 1; });
console.log('\n📚 Kelime kategorileri:');
Object.entries(kategoriler).forEach(([k, v]) => console.log(`  - ${k}: ${v}`));

const tipler = {};
yeniSorular.forEach(s => { tipler[s.tags[0]] = (tipler[s.tags[0]] || 0) + 1; });
console.log('\n❓ Soru bölümleri:');
Object.entries(tipler).forEach(([k, v]) => console.log(`  - ${k}: ${v}`));
